[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

[env]
RUST_LOG = "debug"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/quizmo_test"

[alias]
coverage = "tarpaulin --verbose --all-features --workspace --timeout 120 --out Html"
