name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs
          
      - name: Install cargo-tarpaulin
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-tarpaulin
          version: latest
          use-tool-cache: true

      - name: Run cargo-tarpaulin
        run: |
          # Run regular tests
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --out Html
          # Run doc tests with nightly
          cargo +nightly tarpaulin --doc --verbose --timeout 120 --out Xml --out Html
          
      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: |
            cobertura.xml
            tarpaulin-report.html
          
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          file: cobertura.xml
          fail_ci_if_error: true
